import type { PlatformId } from '@/lib/platforms'

export type ExperienceBadge = 'Best Price' | 'Best Value'
export type ExperienceCategory = 'Tour' | 'Ticket' | 'Activity' | 'Cruise'

export interface PlatformOfferFeatures {
  freeCancellation: boolean
  skipTheLine: boolean
  mobileTicket: boolean
  instantConfirmation: boolean
  guidedOption: boolean
}

export interface PlatformPrice {
  platformId: PlatformId
  price: number
  features: PlatformOfferFeatures
}

export interface Experience {
  id: string
  destinationId: string
  title: string
  city: string
  country: string
  rating: number
  fromPrice: number
  maxPrice: number
  platforms: number
  platformIds: PlatformId[]
  platformPrices: PlatformPrice[]
  badge: ExperienceBadge
  image: string
  description: string
  category: ExperienceCategory
  duration: string
  reviewCount: number
  freeCancellation: boolean
}

export const experiences: Experience[] = [
  // Paris
  {
    id: 'louvre-museum-tour',
    destinationId: 'paris',
    title: 'Louvre Museum Tour',
    city: 'Paris',
    country: 'France',
    rating: 4.7,
    fromPrice: 41,
    maxPrice: 68,
    platforms: 6,
    platformIds: [
      'getyourguide',
      'viator',
      'klook',
      'tiqets',
      'headout',
      'musement',
    ],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 41,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 49,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 49,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'tiqets',
        price: 60,
        features: {
          freeCancellation: true,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'headout',
        price: 60,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'musement',
        price: 68,
        features: {
          freeCancellation: false,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Value',
    image:
      'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&h=520&fit=crop&q=80',
    description:
      'Skip the long lines and explore the world’s largest art museum with a guided visit covering the Mona Lisa, Venus de Milo, and iconic galleries.',
    category: 'Tour',
    duration: '2.5 hours',
    reviewCount: 18420,
    freeCancellation: true,
  },
  {
    id: 'eiffel-tower-summit',
    destinationId: 'paris',
    title: 'Eiffel Tower Summit Access',
    city: 'Paris',
    country: 'France',
    rating: 4.6,
    fromPrice: 36,
    maxPrice: 55,
    platforms: 5,
    platformIds: ['getyourguide', 'viator', 'klook', 'tiqets', 'headout'],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 36,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 43,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 44,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'tiqets',
        price: 52,
        features: {
          freeCancellation: true,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'headout',
        price: 55,
        features: {
          freeCancellation: false,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Price',
    image:
      'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=800&h=520&fit=crop&q=80',
    description:
      'Secure timed entry to the Eiffel Tower with summit access for panoramic views across Paris — compare ticket tiers before you book.',
    category: 'Ticket',
    duration: '1.5 hours',
    reviewCount: 22150,
    freeCancellation: true,
  },
  {
    id: 'seine-river-cruise',
    destinationId: 'paris',
    title: 'Seine River Evening Cruise',
    city: 'Paris',
    country: 'France',
    rating: 4.5,
    fromPrice: 22,
    maxPrice: 39,
    platforms: 6,
    platformIds: [
      'getyourguide',
      'viator',
      'klook',
      'tiqets',
      'headout',
      'civitatis',
    ],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 22,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 27,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 27,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'tiqets',
        price: 34,
        features: {
          freeCancellation: true,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'headout',
        price: 34,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'civitatis',
        price: 39,
        features: {
          freeCancellation: false,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Value',
    image:
      'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800&h=520&fit=crop&q=80',
    description:
      'Cruise past Notre-Dame, the Louvre, and illuminated bridges on an evening Seine ride — a classic Paris experience at a clear from-price.',
    category: 'Cruise',
    duration: '1 hour',
    reviewCount: 9630,
    freeCancellation: true,
  },
  {
    id: 'versailles-day-trip',
    destinationId: 'paris',
    title: 'Versailles Palace Day Trip',
    city: 'Paris',
    country: 'France',
    rating: 4.8,
    fromPrice: 58,
    maxPrice: 95,
    platforms: 5,
    platformIds: ['getyourguide', 'viator', 'klook', 'musement', 'civitatis'],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 58,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 70,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 74,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'musement',
        price: 89,
        features: {
          freeCancellation: true,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'civitatis',
        price: 95,
        features: {
          freeCancellation: false,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Price',
    image:
      'https://images.unsplash.com/photo-1551884170-09fb70a3a2ed?w=800&h=520&fit=crop&q=80',
    description:
      'Visit the Palace of Versailles and its gardens with entry and transport options compared across major booking platforms.',
    category: 'Tour',
    duration: 'Full day',
    reviewCount: 14280,
    freeCancellation: true,
  },

  // Dubai
  {
    id: 'burj-khalifa-tickets',
    destinationId: 'dubai',
    title: 'Burj Khalifa Tickets',
    city: 'Dubai',
    country: 'UAE',
    rating: 4.7,
    fromPrice: 39,
    maxPrice: 72,
    platforms: 5,
    platformIds: ['getyourguide', 'viator', 'klook', 'headout', 'tiqets'],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 39,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 50,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 53,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'headout',
        price: 67,
        features: {
          freeCancellation: true,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'tiqets',
        price: 72,
        features: {
          freeCancellation: false,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Value',
    image:
      'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800&h=520&fit=crop&q=80',
    description:
      'Book At The Top observation deck tickets for the world’s tallest building — compare floors, time slots, and platform prices side by side.',
    category: 'Ticket',
    duration: '1–2 hours',
    reviewCount: 31240,
    freeCancellation: true,
  },
  {
    id: 'desert-safari-dubai',
    destinationId: 'dubai',
    title: 'Desert Safari Dubai',
    city: 'Dubai',
    country: 'UAE',
    rating: 4.6,
    fromPrice: 52,
    maxPrice: 98,
    platforms: 8,
    platformIds: [
      'getyourguide',
      'viator',
      'klook',
      'tiqets',
      'headout',
      'musement',
      'civitatis',
      'tripadvisor',
    ],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 52,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 62,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 62,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'tiqets',
        price: 75,
        features: {
          freeCancellation: true,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'headout',
        price: 75,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'musement',
        price: 88,
        features: {
          freeCancellation: true,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'civitatis',
        price: 88,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'tripadvisor',
        price: 98,
        features: {
          freeCancellation: false,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Price',
    image:
      'https://images.unsplash.com/photo-1451337516015-6b6e9a44a8a3?w=800&h=520&fit=crop&q=80',
    description:
      'Dune bashing, camel rides, and a desert BBQ evening — compare safari packages and inclusions across eight booking platforms.',
    category: 'Activity',
    duration: '6 hours',
    reviewCount: 19870,
    freeCancellation: true,
  },
  {
    id: 'dubai-frame-tickets',
    destinationId: 'dubai',
    title: 'Dubai Frame Entry Tickets',
    city: 'Dubai',
    country: 'UAE',
    rating: 4.4,
    fromPrice: 18,
    maxPrice: 32,
    platforms: 4,
    platformIds: ['getyourguide', 'viator', 'klook', 'headout'],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 18,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 24,
        features: {
          freeCancellation: false,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 26,
        features: {
          freeCancellation: false,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'headout',
        price: 32,
        features: {
          freeCancellation: false,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Value',
    image:
      'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&h=520&fit=crop&q=80',
    description:
      'Walk the glass bridge between old and new Dubai with timed entry tickets compared for the best available rate.',
    category: 'Ticket',
    duration: '1 hour',
    reviewCount: 5420,
    freeCancellation: false,
  },
  {
    id: 'dubai-marina-cruise',
    destinationId: 'dubai',
    title: 'Dubai Marina Dinner Cruise',
    city: 'Dubai',
    country: 'UAE',
    rating: 4.5,
    fromPrice: 45,
    maxPrice: 79,
    platforms: 5,
    platformIds: ['getyourguide', 'viator', 'klook', 'tiqets', 'musement'],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 45,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 57,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 59,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'tiqets',
        price: 74,
        features: {
          freeCancellation: true,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'musement',
        price: 79,
        features: {
          freeCancellation: false,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Price',
    image:
      'https://images.unsplash.com/photo-1582672060674-bc2bd277a6a7?w=800&h=520&fit=crop&q=80',
    description:
      'Dinner cruise along Dubai Marina with skyline views — compare buffet packages and departure times before booking.',
    category: 'Cruise',
    duration: '2 hours',
    reviewCount: 8760,
    freeCancellation: true,
  },

  // Rome
  {
    id: 'colosseum-guided-tour',
    destinationId: 'rome',
    title: 'Colosseum Guided Tour',
    city: 'Rome',
    country: 'Italy',
    rating: 4.6,
    fromPrice: 43,
    maxPrice: 55,
    platforms: 6,
    platformIds: [
      'klook',
      'getyourguide',
      'viator',
      'tiqets',
      'headout',
      'tripcom',
    ],
    platformPrices: [
      {
        platformId: 'klook',
        price: 43,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'getyourguide',
        price: 45,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 48,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'tiqets',
        price: 49,
        features: {
          freeCancellation: false,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'headout',
        price: 52,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'tripcom',
        price: 55,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Price',
    image:
      'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&h=520&fit=crop&q=80',
    description:
      'Explore the iconic Colosseum with an expert guide. Learn about the history of ancient Rome and walk in the footsteps of gladiators.',
    category: 'Tour',
    duration: '2.5 – 3 hours',
    reviewCount: 3245,
    freeCancellation: true,
  },
  {
    id: 'vatican-museums',
    destinationId: 'rome',
    title: 'Vatican Museums Entry',
    city: 'Rome',
    country: 'Italy',
    rating: 4.5,
    fromPrice: 34,
    maxPrice: 62,
    platforms: 5,
    platformIds: [
      'getyourguide',
      'viator',
      'klook',
      'tiqets',
      'tripadvisor',
    ],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 34,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 44,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 45,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'tiqets',
        price: 58,
        features: {
          freeCancellation: true,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'tripadvisor',
        price: 62,
        features: {
          freeCancellation: false,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Value',
    image:
      'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&h=520&fit=crop&q=80',
    description:
      'Timed entry to the Vatican Museums and Sistine Chapel — see which platform offers the best value for your preferred slot.',
    category: 'Ticket',
    duration: '2–3 hours',
    reviewCount: 24110,
    freeCancellation: true,
  },
  {
    id: 'roman-forum-palatine',
    destinationId: 'rome',
    title: 'Roman Forum & Palatine Hill',
    city: 'Rome',
    country: 'Italy',
    rating: 4.7,
    fromPrice: 28,
    maxPrice: 48,
    platforms: 5,
    platformIds: ['getyourguide', 'viator', 'klook', 'tiqets', 'headout'],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 28,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 35,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 36,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'tiqets',
        price: 45,
        features: {
          freeCancellation: true,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'headout',
        price: 48,
        features: {
          freeCancellation: false,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Price',
    image:
      'https://images.unsplash.com/photo-1529260830199-42c24126f198?w=800&h=520&fit=crop&q=80',
    description:
      'Walk ancient Rome with Forum and Palatine Hill access — compare combo tickets and guided options in one place.',
    category: 'Tour',
    duration: '2 hours',
    reviewCount: 11340,
    freeCancellation: true,
  },
  {
    id: 'rome-food-walking-tour',
    destinationId: 'rome',
    title: 'Trastevere Food Walking Tour',
    city: 'Rome',
    country: 'Italy',
    rating: 4.8,
    fromPrice: 65,
    maxPrice: 95,
    platforms: 4,
    platformIds: ['getyourguide', 'viator', 'civitatis', 'musement'],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 65,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 78,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'civitatis',
        price: 82,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'musement',
        price: 95,
        features: {
          freeCancellation: false,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Value',
    image:
      'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=800&h=520&fit=crop&q=80',
    description:
      'Taste Roman classics through Trastevere’s trattorias and markets — compare small-group food tours and inclusions.',
    category: 'Activity',
    duration: '3.5 hours',
    reviewCount: 6890,
    freeCancellation: true,
  },

  // Istanbul
  {
    id: 'hagia-sophia-tickets',
    destinationId: 'istanbul',
    title: 'Hagia Sophia Skip-the-Line',
    city: 'Istanbul',
    country: 'Turkey',
    rating: 4.6,
    fromPrice: 32,
    maxPrice: 52,
    platforms: 5,
    platformIds: ['getyourguide', 'viator', 'klook', 'tiqets', 'headout'],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 32,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 39,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 40,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'tiqets',
        price: 49,
        features: {
          freeCancellation: true,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'headout',
        price: 52,
        features: {
          freeCancellation: false,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Value',
    image:
      'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&h=520&fit=crop&q=80',
    description:
      'Skip-the-line entry to Hagia Sophia with optional audio guide — compare ticket types before you visit Sultanahmet.',
    category: 'Ticket',
    duration: '1–1.5 hours',
    reviewCount: 15620,
    freeCancellation: true,
  },
  {
    id: 'bosphorus-cruise',
    destinationId: 'istanbul',
    title: 'Bosphorus Sunset Cruise',
    city: 'Istanbul',
    country: 'Turkey',
    rating: 4.7,
    fromPrice: 24,
    maxPrice: 45,
    platforms: 6,
    platformIds: [
      'getyourguide',
      'viator',
      'klook',
      'tiqets',
      'civitatis',
      'musement',
    ],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 24,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 30,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 30,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'tiqets',
        price: 39,
        features: {
          freeCancellation: true,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'civitatis',
        price: 39,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'musement',
        price: 45,
        features: {
          freeCancellation: false,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Price',
    image:
      'https://images.unsplash.com/photo-1527838837500-d26570bb48a1?w=800&h=520&fit=crop&q=80',
    description:
      'Sunset cruise along the Bosphorus with views of palaces and mosques — compare boat types and departure times.',
    category: 'Cruise',
    duration: '2 hours',
    reviewCount: 12480,
    freeCancellation: true,
  },
  {
    id: 'grand-bazaar-tour',
    destinationId: 'istanbul',
    title: 'Grand Bazaar Guided Tour',
    city: 'Istanbul',
    country: 'Turkey',
    rating: 4.5,
    fromPrice: 19,
    maxPrice: 35,
    platforms: 4,
    platformIds: ['getyourguide', 'viator', 'klook', 'civitatis'],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 19,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 26,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 28,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'civitatis',
        price: 35,
        features: {
          freeCancellation: false,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Value',
    image:
      'https://images.unsplash.com/photo-1541432901042-2d7640251379?w=800&h=520&fit=crop&q=80',
    description:
      'Navigate the Grand Bazaar with a local guide — compare short walking tours focused on history, crafts, and shopping tips.',
    category: 'Tour',
    duration: '2 hours',
    reviewCount: 4320,
    freeCancellation: true,
  },
  {
    id: 'topkapi-palace-tickets',
    destinationId: 'istanbul',
    title: 'Topkapi Palace Entry',
    city: 'Istanbul',
    country: 'Turkey',
    rating: 4.6,
    fromPrice: 38,
    maxPrice: 58,
    platforms: 5,
    platformIds: ['getyourguide', 'viator', 'klook', 'tiqets', 'headout'],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 38,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 45,
        features: {
          freeCancellation: false,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 46,
        features: {
          freeCancellation: false,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'tiqets',
        price: 55,
        features: {
          freeCancellation: false,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'headout',
        price: 58,
        features: {
          freeCancellation: false,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Price',
    image:
      'https://images.unsplash.com/photo-1541432901042-2d7640251379?w=800&h=520&fit=crop&q=80',
    description:
      'Explore the Ottoman imperial palace and Harem options — compare entry tickets and guided packages across platforms.',
    category: 'Ticket',
    duration: '2–3 hours',
    reviewCount: 9870,
    freeCancellation: false,
  },

  // Cairo
  {
    id: 'pyramids-half-day',
    destinationId: 'cairo',
    title: 'Pyramids of Giza Half-Day Tour',
    city: 'Cairo',
    country: 'Egypt',
    rating: 4.8,
    fromPrice: 29,
    maxPrice: 65,
    platforms: 7,
    platformIds: [
      'getyourguide',
      'viator',
      'klook',
      'tiqets',
      'headout',
      'musement',
      'civitatis',
    ],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 29,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 38,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 38,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'tiqets',
        price: 50,
        features: {
          freeCancellation: true,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'headout',
        price: 50,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'musement',
        price: 62,
        features: {
          freeCancellation: true,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'civitatis',
        price: 65,
        features: {
          freeCancellation: false,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Price',
    image:
      'https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=800&h=520&fit=crop&q=80',
    description:
      'Half-day visit to the Pyramids of Giza and Sphinx with hotel pickup options — compare tour styles and inclusions.',
    category: 'Tour',
    duration: 'Half day',
    reviewCount: 20340,
    freeCancellation: true,
  },
  {
    id: 'egyptian-museum-tour',
    destinationId: 'cairo',
    title: 'Egyptian Museum Guided Tour',
    city: 'Cairo',
    country: 'Egypt',
    rating: 4.6,
    fromPrice: 35,
    maxPrice: 55,
    platforms: 5,
    platformIds: ['getyourguide', 'viator', 'klook', 'tiqets', 'civitatis'],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 35,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 42,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 43,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'tiqets',
        price: 52,
        features: {
          freeCancellation: true,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'civitatis',
        price: 55,
        features: {
          freeCancellation: false,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Value',
    image:
      'https://images.unsplash.com/photo-1572252009281-8c294d7fd667?w=800&h=520&fit=crop&q=80',
    description:
      'Guided tour of Egypt’s treasures including Tutankhamun highlights — compare museum entry and guide packages.',
    category: 'Tour',
    duration: '3 hours',
    reviewCount: 7650,
    freeCancellation: true,
  },
  {
    id: 'khan-el-khalili-tour',
    destinationId: 'cairo',
    title: 'Khan el-Khalili Bazaar Tour',
    city: 'Cairo',
    country: 'Egypt',
    rating: 4.5,
    fromPrice: 15,
    maxPrice: 28,
    platforms: 4,
    platformIds: ['getyourguide', 'viator', 'klook', 'civitatis'],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 15,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 20,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 23,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'civitatis',
        price: 28,
        features: {
          freeCancellation: false,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Price',
    image:
      'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&h=520&fit=crop&q=80',
    description:
      'Explore Cairo’s historic bazaar with a local guide — compare short walking tours focused on culture and shopping.',
    category: 'Activity',
    duration: '2 hours',
    reviewCount: 3180,
    freeCancellation: true,
  },
  {
    id: 'cairo-nile-dinner-cruise',
    destinationId: 'cairo',
    title: 'Nile Dinner Cruise',
    city: 'Cairo',
    country: 'Egypt',
    rating: 4.4,
    fromPrice: 42,
    maxPrice: 70,
    platforms: 5,
    platformIds: ['getyourguide', 'viator', 'klook', 'headout', 'musement'],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 42,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 52,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 53,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'headout',
        price: 66,
        features: {
          freeCancellation: true,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'musement',
        price: 70,
        features: {
          freeCancellation: false,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Value',
    image:
      'https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=800&h=520&fit=crop&q=80',
    description:
      'Dinner cruise on the Nile with entertainment options — compare packages and departure points across platforms.',
    category: 'Cruise',
    duration: '2 hours',
    reviewCount: 5940,
    freeCancellation: true,
  },

  // Santorini
  {
    id: 'santorini-caldera-cruise',
    destinationId: 'santorini',
    title: 'Caldera Catamaran Cruise',
    city: 'Santorini',
    country: 'Greece',
    rating: 4.9,
    fromPrice: 89,
    maxPrice: 145,
    platforms: 5,
    platformIds: ['getyourguide', 'viator', 'klook', 'headout', 'civitatis'],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 89,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 106,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 114,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'headout',
        price: 134,
        features: {
          freeCancellation: true,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'civitatis',
        price: 145,
        features: {
          freeCancellation: false,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Value',
    image:
      'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&h=520&fit=crop&q=80',
    description:
      'Catamaran cruise around the caldera with swimming stops and sunset views — compare lunch vs sunset sail packages.',
    category: 'Cruise',
    duration: '5 hours',
    reviewCount: 11290,
    freeCancellation: true,
  },
  {
    id: 'oia-sunset-tour',
    destinationId: 'santorini',
    title: 'Oia Sunset Walking Tour',
    city: 'Santorini',
    country: 'Greece',
    rating: 4.7,
    fromPrice: 28,
    maxPrice: 48,
    platforms: 4,
    platformIds: ['getyourguide', 'viator', 'klook', 'civitatis'],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 28,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 37,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 39,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'civitatis',
        price: 48,
        features: {
          freeCancellation: false,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Price',
    image:
      'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800&h=520&fit=crop&q=80',
    description:
      'Walk Oia’s cliffside paths and catch the famous sunset with a local guide — compare small-group evening tours.',
    category: 'Tour',
    duration: '2 hours',
    reviewCount: 4560,
    freeCancellation: true,
  },
  {
    id: 'santorini-wine-tasting',
    destinationId: 'santorini',
    title: 'Santorini Wine Tasting Tour',
    city: 'Santorini',
    country: 'Greece',
    rating: 4.8,
    fromPrice: 72,
    maxPrice: 110,
    platforms: 4,
    platformIds: ['getyourguide', 'viator', 'klook', 'musement'],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 72,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 88,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 94,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'musement',
        price: 110,
        features: {
          freeCancellation: false,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Value',
    image:
      'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=800&h=520&fit=crop&q=80',
    description:
      'Visit volcanic vineyards and taste Assyrtiko wines with caldera views — compare tasting tours and transfer options.',
    category: 'Activity',
    duration: '4 hours',
    reviewCount: 6780,
    freeCancellation: true,
  },
  {
    id: 'akrotiri-archaeological',
    destinationId: 'santorini',
    title: 'Akrotiri Archaeological Site',
    city: 'Santorini',
    country: 'Greece',
    rating: 4.6,
    fromPrice: 22,
    maxPrice: 40,
    platforms: 5,
    platformIds: ['getyourguide', 'viator', 'klook', 'tiqets', 'headout'],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 22,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 29,
        features: {
          freeCancellation: false,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 29,
        features: {
          freeCancellation: false,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'tiqets',
        price: 38,
        features: {
          freeCancellation: false,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'headout',
        price: 40,
        features: {
          freeCancellation: false,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Price',
    image:
      'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&h=520&fit=crop&q=80',
    description:
      'Explore the Bronze Age ruins of Akrotiri with entry and guided options — compare tickets before you go.',
    category: 'Ticket',
    duration: '1.5 hours',
    reviewCount: 2890,
    freeCancellation: false,
  },

  // Barcelona
  {
    id: 'sagrada-familia-tickets',
    destinationId: 'barcelona',
    title: 'Sagrada Familia Entry',
    city: 'Barcelona',
    country: 'Spain',
    rating: 4.8,
    fromPrice: 38,
    maxPrice: 65,
    platforms: 6,
    platformIds: [
      'getyourguide',
      'viator',
      'klook',
      'tiqets',
      'headout',
      'musement',
    ],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 38,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 46,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 46,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'tiqets',
        price: 57,
        features: {
          freeCancellation: true,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'headout',
        price: 57,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'musement',
        price: 65,
        features: {
          freeCancellation: false,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Value',
    image:
      'https://images.unsplash.com/photo-1523531294919-4bcd7c65e216?w=800&h=520&fit=crop&q=80',
    description:
      'Timed entry to Gaudí’s masterpiece with tower and audio-guide options — compare platforms for the best slot price.',
    category: 'Ticket',
    duration: '1.5–2 hours',
    reviewCount: 28940,
    freeCancellation: true,
  },
  {
    id: 'park-guell-tickets',
    destinationId: 'barcelona',
    title: 'Park Güell Guided Visit',
    city: 'Barcelona',
    country: 'Spain',
    rating: 4.6,
    fromPrice: 26,
    maxPrice: 45,
    platforms: 5,
    platformIds: ['getyourguide', 'viator', 'klook', 'tiqets', 'civitatis'],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 26,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 33,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 34,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'tiqets',
        price: 42,
        features: {
          freeCancellation: true,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'civitatis',
        price: 45,
        features: {
          freeCancellation: false,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Price',
    image:
      'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800&h=520&fit=crop&q=80',
    description:
      'Guided visit to Park Güell’s monumental zone — compare entry-only vs guided packages across booking sites.',
    category: 'Tour',
    duration: '1.5 hours',
    reviewCount: 13450,
    freeCancellation: true,
  },
  {
    id: 'barcelona-gothic-quarter',
    destinationId: 'barcelona',
    title: 'Gothic Quarter Walking Tour',
    city: 'Barcelona',
    country: 'Spain',
    rating: 4.7,
    fromPrice: 18,
    maxPrice: 35,
    platforms: 4,
    platformIds: ['getyourguide', 'viator', 'klook', 'civitatis'],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 18,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 26,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 27,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'civitatis',
        price: 35,
        features: {
          freeCancellation: false,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Value',
    image:
      'https://images.unsplash.com/photo-1562883676-8c7feb83f09b?w=800&h=520&fit=crop&q=80',
    description:
      'Discover medieval streets, plazas, and hidden corners of the Gothic Quarter — compare walking tours and group sizes.',
    category: 'Tour',
    duration: '2 hours',
    reviewCount: 8120,
    freeCancellation: true,
  },
  {
    id: 'camp-nou-tour',
    destinationId: 'barcelona',
    title: 'Camp Nou Stadium Tour',
    city: 'Barcelona',
    country: 'Spain',
    rating: 4.5,
    fromPrice: 32,
    maxPrice: 55,
    platforms: 5,
    platformIds: ['getyourguide', 'viator', 'klook', 'tiqets', 'headout'],
    platformPrices: [
      {
        platformId: 'getyourguide',
        price: 32,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'viator',
        price: 40,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'klook',
        price: 42,
        features: {
          freeCancellation: true,
          skipTheLine: true,
          mobileTicket: false,
          instantConfirmation: true,
          guidedOption: true,
        },
      },
      {
        platformId: 'tiqets',
        price: 51,
        features: {
          freeCancellation: true,
          skipTheLine: false,
          mobileTicket: true,
          instantConfirmation: true,
          guidedOption: false,
        },
      },
      {
        platformId: 'headout',
        price: 55,
        features: {
          freeCancellation: false,
          skipTheLine: true,
          mobileTicket: true,
          instantConfirmation: false,
          guidedOption: true,
        },
      },
    ],
    badge: 'Best Price',
    image:
      'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&h=520&fit=crop&q=80',
    description:
      'Tour Camp Nou’s stands, museum, and pitchside areas — compare stadium experience tickets across platforms.',
    category: 'Activity',
    duration: '2 hours',
    reviewCount: 16780,
    freeCancellation: true,
  },
]
